### ISSUE TITLE
awesome-hyperscript repo

### ISSUE THREAD

**Issue by balupton** [hyperhype/hyperscript#64]
looking through https://npms.io/search?q=hyperscript I was surprised as how big and cool the ecosystem is around this, notably:

- https://github.com/substack/hyperx and https://github.com/queckezz/elementx are like http://coffeekup.org
- https://github.com/hyperapp/hyperapp - for react style apps
- https://github.com/Matt-Esch/virtual-dom
- https://github.com/twilson63/material-hyperscript

and so on

would be cool for the awesome-list style repo for people to add their own

of course this could be a wiki page, however it seems the awesome-list repo stuff is better for discoverability as they show up in searches and people can watch and star them

**Comment by dominictarr** [comment]
yes, this a great idea - @ahdinosaur set up basically this for pull-streams, https://github.com/pull-stream/pull-stream-docs which turns into a website at http://pull-stream.github.io/  it was great for the sense of community actually because someone would write a module and then PR it to the docs, or if you saw someone doing something cool you could invite them to make that PR.

**Comment by ahdinosaur** [comment]
@balupton :+1:, i think an awesome-list style repo called `awesome-hyperscript` would be great!

in the case of `pull-stream-docs`, i feel that is documentation for an ecosystem of cohesive composable modules (inspired by http://scijs.net/packages/ and http://stack.gl/packages/), rather than an awesome-list style repo documenting a wide and diverse ecosystem of anything regarding some center, which does feel more appropriate for the `hyperscript` ecosystem where it's more loose.

support whatever you have in mind. :heart:

**Comment by balupton** [comment]
sweet, so someone want to create the `hyperhype/awesome-hyperscript` repo? I can kickstart it once given permission if you fellows want.

**Comment by dominictarr** [comment]
@balupton just sent you an invite to be hyperhype co-owner, you can create repos, add other people as owners, anything!

**Comment by balupton** [comment]
https://github.com/hyperhype/awesome-hyperscript

**Comment by balupton** [comment]
alright, I added topics and descriptions to most of the other repos - and did a intro commit for the awesome-hyperscript repo

@dominictarr @ahdinosaur do you think that having the uses official package vs api compatible package is a good distinguishment to make? I think it is, but not sure on the current approach. I think if there was a description somewhere with the goals of hyperscript (in regards to API compatible vs uses hyperhyper/hyperscript) at the top, that would be swell.
